apiVersion: v1
kind: Pod
metadata:
  name: busypod-restricted
spec:
  containers:
    - image: busybox
      name: busybox
      command: ["sh", "-c", 'while true; do echo "Running..."; sleep 2h; done']
      imagePullPolicy: Always
      securityContext:
        runAsUser: 3000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: "RuntimeDefault"
